before_install:
 - cd fRequent

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

after_success:
  - Rscript -e 'pkgdown::build_site()'


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
